name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  animations: ^2.0.11
  awesome_extensions: ^2.0.17
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  core:
    path: ../core
  dio: ^5.7.0
  easy_animated_indexed_stack: ^0.0.2
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2
  window_manager: ^0.4.2

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.prod
    - assets/image/
    - assets/icon/
  fonts:
    - family: DMSerifDisplay
      fonts:
        - asset: assets/font/DMSerifDisplay-Regular.ttf
    - family: Kantumruy
      fonts:
        - asset: assets/font/Kantumruy-Regular.ttf
        - asset: assets/font/Kantumruy-Bold.ttf
          weight: 700
        - asset: assets/font/Kantumruy-Light.ttf
          weight: 300
    - family: Krylon
      fonts:
        - asset: assets/font/Krylon-Regular.otf
    - family: Comforter
      fonts:
        - asset: assets/font/Comforter-Regular.ttf
    - family: Calibri
      fonts:
        - asset: assets/font/calibri_regular.ttf
    - family: ElMessiri
      fonts:
        - asset: assets/font/ElMessiri-Regular.ttf
        - asset: assets/font/ElMessiri-Medium.ttf
          weight: 500
        - asset: assets/font/ElMessiri-SemiBold.ttf
          weight: 600
        - asset: assets/font/ElMessiri-Bold.ttf
          weight: 700

flutter_assets:
  assets_path:
    - assets/image/
    - assets/icon/
  output_path: lib/constants/
  filename: assets.dart
  field_prefix:
  ignore_comments: true
