name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  animations: ^2.0.11
  awesome_extensions: ^2.0.17
  core:
    path: ../core
  dio: ^5.7.0
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  logger: ^2.4.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.prod
    - assets/images/
  fonts:
    - family: DMSerifDisplay
      fonts:
        - asset: assets/fonts/DMSerifDisplay-Regular.ttf
    - family: KantumruyPro
      fonts:
        - asset: assets/fonts/KantumruyPro-Regular.ttf
        - asset: assets/fonts/KantumruyPro-Bold.ttf
          weight: 700
    - family: Krylon
      fonts:
        - asset: assets/fonts/Krylon-Regular.otf

flutter_assets:
  assets_path:
    - assets/images/
  output_path: lib/constants/
  filename: assets.dart
  field_prefix:
  ignore_comments: true
