name: backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  core:
    path: ../core
  crypto: ^3.0.5
  dart_frog: ^1.1.0
  logger: ^2.4.0
  mongo_dart: ^0.10.3
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
