name: backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  core:
    path: ../core
  dart_frog: ^1.1.0
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  mocktail: ^1.0.3
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  test: ^1.25.5
  very_good_analysis: ^5.1.0
