name: Deploy Dart Frog Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'core/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
    
    - name: Install Dependencies
      run: |
        cd backend
        dart pub get
        cd ../core
        dart pub get
    
    - name: Install Globe CLI
      run: dart pub global activate globe_cli
    
    - name: Build Dart Frog project
      run: |
        cd backend
        dart pub global run globe_cli build
    
    - name: Deploy to Globe
      run: |
        cd backend
        dart pub global run globe_cli deploy
      env:
        GLOBE_TOKEN: ${{ secrets.GLOBE_TOKEN }}