name: Deploy Dart Frog Backend

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/publish_backend.yaml'
      - 'backend/**'
      - 'core/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
    
    - name: Install Dependencies
      run: |
        cd backend
        dart pub get
        cd ..
    
    - name: Install Globe CLI
      run: dart pub global activate globe_cli
    
    - name: Deploy to Globe
      run: globe deploy --token=${{ secrets.GLOBE_TOKEN }} --project="${{ secrets.GLOBE_PROJECT_ID }}"